# Header
menu:
  Home: /
  Archives: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "#"
  # weibo: "#"
  # rss: "#"
  # facebook: "#"
  # google: "#"
  twitter: "#"
  linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "https://avatars1.githubusercontent.com/u/845750?v=2&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
#是否开启云标签s
tagcloud: true