# Header
menu:
  Home: /
  Archives: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "#"
  # weibo: "#"
  # rss: "#"
  # facebook: "#"
  # google: "#"
  twitter: "#"
  linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

avatar: "https://avatars1.githubusercontent.com/u/845750?v=2&s=460"
